### ISSUE TITLE
Wrong parsing of "content-disposition" header

### ISSUE THREAD

**Issue by MichalSchwarz** [oussama1598/node-filedownloader#1]
Filename encapsulation by doublequotes is not required. http://tools.ietf.org/html/rfc2183 . Header can look like this: `"attachment; filename=debian-6.0.4-amd64-netinst.iso"`

In this case is result of
```javascript
var filename = res.headers['content-disposition'].split(";");
filename = filename[1].replace('filename="', "");
filename = filename.substr(1, filename.length - 2);
```
this: `filename=debian-6.0.4-amd64-netinst.is`

I've found this package: https://www.npmjs.com/package/content-disposition
What do you think?

**Comment by oussama1598** [comment]
ok i will see about it !! and thanks for your help

**Comment by oussama1598** [comment]
Fixed!!
