### ISSUE TITLE
All downloads on windows giving error 'Can't start the download'

### ISSUE THREAD

**Issue by gauravraj** [oussama1598/node-filedownloader#2]
I'm using filedownloader version 1.2.0 in my project. I'm using it to download and save files in a given location. Its working perfectly fine in Ubuntu but when I used it on Windows, its constantly giving me the error 'Can't start the download'. Even after giving the error, the file has been downloaded perfectly and saved in the given location. 'start', 'progress' or 'end' events are never called during the download. What could be the reason behind this? Please help.

**Comment by oussama1598** [comment]
thanks for mentioning the problem it is fixed now 

Note: the problem have nothing to do with the operating system, it was a mistake of me checking the progress, in your case the progress never changed and stayed at 0

**Comment by oussama1598** [comment]
please update the dependency to get the last version (1.2.2)
